# Generated by Django 5.1.5 on 2025-02-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_images_alter_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_of_jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='metal_color',
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_jewelry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category_of_jewelry'),
        ),
    ]
