# Generated by Django 5.1.5 on 2025-02-03 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_intended_to_alter_product_time_create_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories_of_precious_stones',
            new_name='Categories_of_stones',
        ),
        migrations.RenameModel(
            old_name='Precious_stones',
            new_name='Stones',
        ),
        migrations.AlterModelOptions(
            name='categories_of_materials',
            options={'verbose_name_plural': 'Category of materials'},
        ),
        migrations.AlterModelOptions(
            name='categories_of_metal',
            options={'verbose_name_plural': 'Category of metal'},
        ),
        migrations.AlterModelOptions(
            name='categories_of_stones',
            options={'verbose_name_plural': 'Category of stones'},
        ),
        migrations.AlterModelOptions(
            name='category_of_jewelry',
            options={'verbose_name_plural': 'Category of jewelry'},
        ),
        migrations.AlterModelOptions(
            name='intended_to',
            options={'verbose_name_plural': 'Intended to'},
        ),
        migrations.AlterModelOptions(
            name='stones',
            options={'verbose_name_plural': 'Stones'},
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_jewelry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_of_jewelry', to='product.category_of_jewelry'),
        ),
    ]
