# Generated by Django 5.1.5 on 2025-02-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_categories_of_precious_stones_categories_of_stones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types_of_stones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Type of stones',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stones',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stones', to='product.categories_of_stones'),
        ),
        migrations.AddField(
            model_name='stones',
            name='type_of_stone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='type_of_stones', to='product.types_of_stones'),
            preserve_default=False,
        ),
    ]
