# Generated by Django 5.1.5 on 2025-02-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_types_of_stones_alter_product_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stones',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories_of_stones', to='product.categories_of_stones'),
        ),
    ]
