# Generated by Django 5.1.5 on 2025-02-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_stones_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stones_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Stones base',
            },
        ),
        migrations.AlterField(
            model_name='stones',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories_of_stones', to='product.categories_of_stones'),
        ),
        migrations.AlterField(
            model_name='stones',
            name='type_of_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_of_stones', to='product.types_of_stones'),
        ),
        migrations.AddField(
            model_name='stones',
            name='base_of_stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_of_stones', to='product.stones_base'),
        ),
    ]
