# Generated by Django 5.1.5 on 2025-02-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_stones_base_alter_stones_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stones', to='product.stones'),
        ),
    ]
